extends RefCounted
## structures.gd — Registry of all playable structures for the History in Voxels
## slice. Every cell coordinate is generated by pure math (ring/fill/column
## helpers) from the real plan of each structure — no eyeballing, per project
## rule. Each structure carries its own palette, limits, and unique flavour text
## written in the core emotional register: the works of man return to the earth,
## but the Builder remembers.

## ---- Cell-generation helpers (pure math) ----

## Fill a solid rectangle at height y.
static func _fill(x0: int, x1: int, z0: int, z1: int, y: int, mat: String) -> Dictionary:
	var d := {}
	for x in range(x0, x1 + 1):
		for z in range(z0, z1 + 1):
			d[Vector3i(x, y, z)] = mat
	return d

## Perimeter ring of a rectangle at height y (hollow middle).
static func _ring(x0: int, x1: int, z0: int, z1: int, y: int, mat: String) -> Dictionary:
	var d := {}
	for x in range(x0, x1 + 1):
		for z in range(z0, z1 + 1):
			if x == x0 or x == x1 or z == z0 or z == z1:
				d[Vector3i(x, y, z)] = mat
	return d

## A vertical column of h blocks at (x, z), starting at y0.
static func _col(x: int, z: int, y0: int, h: int, mat: String) -> Dictionary:
	var d := {}
	for y in range(y0, y0 + h):
		d[Vector3i(x, y, z)] = mat
	return d

## Merge several cell dicts (later wins on overlap).
static func _merge(dicts: Array) -> Dictionary:
	var out := {}
	for d in dicts:
		out.merge(d)
	return out

## ---- Registry ----
static func structures() -> Array[Dictionary]:
	return [
		_gobekli(),
		_mastaba(),
		_pyramid(),
		_ur_ziggurat(),
		_great_bath(),
		_persepolis_gate(),
		_great_wall(),
		_parthenon(),
		_colosseum(),
		_diorama_debug(),
	]


## 10 · DIORAMA DEBUG — empty level that renders ONLY the environmental stage
## (no build target, no baseplate, no floor, no HUD). For isolating diorama
## prop rendering on device.
static func _diorama_debug() -> Dictionary:
	return {
		"id": "diorama_debug",
		"site_era": "DIORAMA DEBUG — stage only",
		"colors": {},
		"core": {},
		"zenith": {},
		"limits": Vector3(3.0, 3.0, 2.0),
		"beat1_msg": "Stage-only debug view.",
		"beat2_msg": "",
		"excavation_msg": "",
		"epilogue": [],
	}


## --------------------------------------------------------------------------
## 1 · GÖBEKLI ENCLOSURE A — Turkey, ~9500 BCE (first temple, deliberate burial)
## --------------------------------------------------------------------------
static func _gobekli() -> Dictionary:
	var colors := {
		"limestone": Color("#E8DCC8"),
		"weathered": Color("#B8A88A"),
		"dust":      Color("#D9C089"),
		"rubble":    Color("#8A7A5E"),
	}
	# Ring of 4 T-pillars + 2 central T-pillars. Stem 2 tall; cap 3 wide.
	var ring_pos := [Vector2i(-2, 0), Vector2i(2, 0), Vector2i(0, -2), Vector2i(0, 2)]
	var center_pos := [Vector2i(0, -1), Vector2i(0, 1)]
	var core := {}
	var zenith := {}
	for p in ring_pos + center_pos:
		core.merge(_col(p.x, p.y, 0, 2, "limestone"))       # stem
		zenith.merge(_fill(p.x - 1, p.x + 1, p.y, p.y, 2, "limestone"))  # T-cap
	return {
		"id": "gobekli",
		"site_era": "Göbekli Enclosure A — Şanlıurfa, Turkey · ~9500 BCE",
		"colors": colors,
		"core": core,
		"zenith": zenith,
		"survivor": _merge([
			_col(-2, 0, 0, 1, "weathered"), _col(2, 0, 0, 1, "weathered"),
			_col(0, -1, 0, 1, "weathered"),
		]),
		"limits": Vector3(3.0, 3.0, 2.0),
		"beat1_msg": "Set the first stones of the oldest temple on earth.",
		"beat2_msg": "The pillars stand.\nSet their T-caps — the heads of the forgotten gods.",
		"epilogue": [
			"Ten thousand years before the pyramids, hands like yours raised stone.",
			"They buried their own temple — the earth kept it whole.",
		],
		"excavation_msg": "The hollows filled with dust and time. Clear the first stones of the temple.",
		"beat_pieces": {2: [{"id": "t_cap", "color": "limestone"}]},
		"fact": "Göbekli Tepe (~9500 BCE) was deliberately buried by its own builders — the world's first temple, hidden for nine millennia.",
	}


## --------------------------------------------------------------------------
## 2 · MASTABA OF TI — Saqqara, Egypt · ~2400 BCE (the house of eternity)
## --------------------------------------------------------------------------
static func _mastaba() -> Dictionary:
	var colors := {
		"mudbrick":   Color("#C08552"),
		"mudbrick_old": Color("#9C6B3F"),
		"limestone":  Color("#F2EBD9"),
		"redband":    Color("#C1440E"),
		"dust":       Color("#E0C9A6"),
		"rubble":     Color("#8A7A5E"),
	}
	var core := _merge([
		_fill(-2, 2, -1, 1, 0, "mudbrick"),   # base 5x3
		_fill(-1, 1, 0, 0, 1, "mudbrick"),    # upper tier 3x1
	])
	var zenith := _merge([
		_fill(-1, 1, 0, 0, 2, "redband"),                       # cornice
		_col(2, -1, 1, 1, "limestone"), _col(2, 1, 1, 1, "limestone"),
		_col(2, -1, 0, 1, "limestone"), _col(2, 1, 0, 1, "limestone"),
		_col(3, 0, 0, 1, "limestone"),                          # offering table
	])
	var survivor := _merge([
		_fill(-2, -1, -1, 1, 0, "mudbrick_old"),
		_fill(0, 0, -1, 0, 0, "mudbrick_old"),
		_fill(1, 2, 1, 1, 0, "mudbrick_old"),
		_col(3, 0, 0, 1, "limestone"),
	])
	return {
		"id": "mastaba",
		"site_era": "Mastaba of Ti — Saqqara, Egypt · ~2400 BCE",
		"colors": colors,
		"core": core,
		"zenith": zenith,
		"survivor": survivor,
		"limits": Vector3(3.0, 3.0, 1.0),
		"beat1_msg": "The house of eternity — lay its mudbrick walls.",
		"beat2_msg": "The tomb stands.\nRestore its zenith — limestone, cornice, offering table.",
		"epilogue": [
			"Every work of man returns to the earth.",
			"Yet the house of eternity stood four thousand years.",
		],
		"excavation_msg": "The desert filled the tomb. Clear the sand from the house of eternity.",
		"fact": "Mastaba of Ti, Saqqara (~2400 BCE): a tomb whose painted walls once told the whole life of an Egyptian official.",
	}


## --------------------------------------------------------------------------
## 3 · PYRAMID OF GIZA — Egypt · ~2560 BCE (stepped core, casing, capstone)
## --------------------------------------------------------------------------
static func _pyramid() -> Dictionary:
	var colors := {
		"limestone": Color("#F2EBD9"),
		"casing":    Color("#FFF8E7"),
		"gold":      Color("#D4A017"),
		"weathered": Color("#CFC3A5"),
		"dust":      Color("#E0C9A6"),
		"rubble":    Color("#8A7A5E"),
	}
	var core := _merge([
		_fill(-2, 2, -2, 2, 0, "limestone"),   # base 5x5
		_fill(-1, 1, -1, 1, 1, "limestone"),   # mid 3x3
	])
	var zenith := _merge([
		_fill(-1, 1, -1, 1, 2, "casing"),      # casing tier 3x3
		_col(0, 0, 3, 1, "gold"),              # capstone
	])
	var survivor := _merge([
		_fill(-2, 2, -2, -1, 0, "weathered"),
		_fill(-1, 1, 0, 0, 0, "weathered"),
		_fill(-2, 2, 1, 2, 0, "weathered"),
	])
	return {
		"id": "pyramid",
		"site_era": "Pyramid of Giza — Giza, Egypt · ~2560 BCE",
		"colors": colors,
		"core": core,
		"zenith": zenith,
		"survivor": survivor,
		"limits": Vector3(2.0, 4.0, 2.0),
		"beat1_msg": "A mountain of stone for the king — lay its first course.",
		"beat2_msg": "The mountain holds.\nCase it in white — set the golden capstone.",
		"epilogue": [
			"A king built a mountain so his name would never die.",
			"The mountain kept the stone and gave the name to the wind.",
		],
		"excavation_msg": "The white casing fell, the gold capstone lost. Clear the dust of millennia.",
		"fact": "Giza (~2560 BCE): 2.3 million blocks, each heavier than the one in your hand — the only ancient wonder still standing.",
	}


## --------------------------------------------------------------------------
## 4 · GREAT ZIGGURAT OF UR — Iraq · ~2100 BCE (stair of the moon god)
## --------------------------------------------------------------------------
static func _ur_ziggurat() -> Dictionary:
	var colors := {
		"mudbrick":   Color("#C08552"),
		"baked brick": Color("#B0552E"),
		"weathered":  Color("#9C6B3F"),
		"dust":       Color("#D9C089"),
		"rubble":     Color("#8A7A5E"),
	}
	var core := _merge([
		_fill(-2, 2, -1, 1, 0, "mudbrick"),   # base 5x3
		_fill(-1, 1, 0, 0, 1, "mudbrick"),    # mid 3x1
		_col(0, 0, 2, 1, "mudbrick"),         # top shrine platform
	])
	var zenith := _merge([
		_col(0, 0, 3, 1, "baked brick"),      # shrine (moon god's house)
		_col(0, 0, 2, 0, "baked brick"),      # (redundant no-op, kept for clarity)
		_fill(-2, 2, 1, 1, 1, "baked brick"), # facing band on the upper face
	])
	return {
		"id": "ur",
		"site_era": "Great Ziggurat of Ur — Iraq · ~2100 BCE",
		"colors": colors,
		"core": core,
		"zenith": zenith,
		"survivor": _merge([
			_fill(-2, 2, -1, 0, 0, "weathered"),
			_fill(-1, 1, 1, 1, 0, "weathered"),
			_fill(-1, 1, 0, 0, 1, "weathered"),
		]),
		"limits": Vector3(2.0, 4.0, 1.0),
		"beat1_msg": "The stair between earth and sky — build it course by course.",
		"beat2_msg": "The stair is whole.\nFace it in baked brick — the road the gods walk down.",
		"epilogue": [
			"The moon-god's stair rose above the plain for four thousand years.",
			"The rains unbuilt it course by course.",
		],
		"excavation_msg": "The rains washed the facing away. Clear the mound where the stair stood.",
		"fact": "The Ziggurat of Ur (~2100 BCE) was dedicated to the moon god Nanna — its mudbrick core was once faced with gleaming baked brick.",
	}


## --------------------------------------------------------------------------
## 5 · GREAT BATH — Mohenjo-daro, Indus Valley · ~2500 BCE (the sacred pool)
## --------------------------------------------------------------------------
static func _great_bath() -> Dictionary:
	var colors := {
		"baked brick": Color("#B0552E"),
		"water":       Color("#3E7C9F"),
		"limestone":   Color("#F2EBD9"),
		"weathered":   Color("#8A5A33"),
		"dust":        Color("#D9C089"),
		"rubble":      Color("#8A7A5E"),
	}
	var core := _ring(-2, 2, -1, 1, 0, "baked brick")   # pool rim 5x3
	var zenith := _merge([
		_fill(-1, 1, 0, 0, 0, "water"),                 # the sacred water
		_col(-2, -1, 1, 1, "limestone"), _col(2, 1, 1, 1, "limestone"),  # corner caps
		_col(-2, 1, 1, 1, "limestone"), _col(2, -1, 1, 1, "limestone"),
	])
	return {
		"id": "bath",
		"site_era": "The Great Bath — Mohenjo-daro · ~2500 BCE",
		"colors": colors,
		"core": core,
		"zenith": zenith,
		"survivor": _merge([
			_ring(-2, 2, -1, 1, 0, "weathered"),
		]),
		"limits": Vector3(2.0, 2.0, 1.0),
		"beat1_msg": "The oldest pool in the world — ring it with brick.",
		"beat2_msg": "The walls hold.\nBring the water — the sacred pool fills.",
		"epilogue": [
			"The city of Mohenjo-daro is gone; its drains still carry water.",
			"The brick outlived its makers.",
		],
		"excavation_msg": "Silt filled the sacred pool. Clear it down to the brick.",
		"fact": "The Great Bath (~2500 BCE) is the oldest public water tank in the world — proof the Indus people mastered plumbing 4,500 years ago.",
	}


## --------------------------------------------------------------------------
## 6 · GATE OF ALL NATIONS — Persepolis · ~470 BCE (doorway of an empire)
## --------------------------------------------------------------------------
static func _persepolis_gate() -> Dictionary:
	var colors := {
		"limestone": Color("#E8DCC8"),
		"glazed":    Color("#2A6F97"),
		"weathered": Color("#B8A88A"),
		"dust":      Color("#D9C089"),
		"rubble":    Color("#8A7A5E"),
	}
	# 2x2 columns, 2 tall.
	var core := _merge([
		_col(-1, -1, 0, 2, "limestone"), _col(1, -1, 0, 2, "limestone"),
		_col(-1, 1, 0, 2, "limestone"), _col(1, 1, 0, 2, "limestone"),
	])
	var zenith := _merge([
		_fill(-1, 1, -1, 1, 2, "limestone"),  # roof slab on the four column tops
		_col(-1, 0, 3, 1, "glazed"), _col(1, 0, 3, 1, "glazed"),
		_col(0, -1, 3, 1, "glazed"), _col(0, 1, 3, 1, "glazed"),  # glazed trim
	])
	return {
		"id": "persepolis",
		"site_era": "Gate of All Nations — Persepolis · ~470 BCE",
		"colors": colors,
		"core": core,
		"zenith": zenith,
		"survivor": _merge([
			_col(-1, -1, 0, 1, "weathered"), _col(1, -1, 0, 1, "weathered"),
			_col(-1, 1, 0, 1, "weathered"),
		]),
		"limits": Vector3(1.0, 4.0, 1.0),
		"beat1_msg": "An empire's doorway — set its four columns.",
		"beat2_msg": "The four columns stand ready.\nSet the roof and the glazed trim of the king's gate.",
		"epilogue": [
			"Alexander burned the gate; two centuries of kings had passed beneath it.",
			"The fire is ash, the columns stand.",
		],
		"excavation_msg": "Alexander's fire fell to ash. Clear it from the king's gate.",
		"beat_pieces": {2: [{"id": "plate_3x3", "color": "limestone"}]},
		"fact": "Persepolis (~470 BCE): every emissary of the Persian empire passed through this gate — the bull reliefs watched them all.",
	}


## --------------------------------------------------------------------------
## 7 · GREAT WALL WATCHTOWER — China · ~200 BCE (one brick of the dragon)
## --------------------------------------------------------------------------
static func _great_wall() -> Dictionary:
	var colors := {
		"brick":    Color("#B0703C"),
		"banner":   Color("#B03030"),
		"weathered": Color("#8A5A33"),
		"dust":     Color("#D9C089"),
		"rubble":   Color("#8A7A5E"),
	}
	var core := _merge([
		_fill(-1, 1, -1, 1, 0, "brick"),   # tower base 3x3
		_fill(-1, 1, -1, 1, 1, "brick"),   # tower second tier
	])
	var zenith := _merge([
		_col(-1, -1, 2, 1, "brick"), _col(1, -1, 2, 1, "brick"),
		_col(-1, 1, 2, 1, "brick"), _col(1, 1, 2, 1, "brick"),   # crenellations
		_col(2, 0, 0, 1, "brick"), _col(2, 0, 1, 1, "brick"),    # wall east
		_col(-2, 0, 0, 1, "brick"), _col(-2, 0, 1, 1, "brick"),  # wall west
		_col(0, 0, 2, 1, "banner"),                              # the banner, atop the tower's roof
	])
	return {
		"id": "wall",
		"site_era": "Great Wall Watchtower — China · ~200 BCE",
		"colors": colors,
		"core": core,
		"zenith": zenith,
		"survivor": _merge([
			_fill(-1, 1, -1, 1, 0, "weathered"),
			_col(2, 0, 0, 1, "weathered"),
		]),
		"limits": Vector3(2.0, 3.0, 1.0),
		"beat1_msg": "One brick of the dragon — begin the watchtower.",
		"beat2_msg": "The tower stands.\nSet its crenellations, its walls, its banner.",
		"epilogue": [
			"Ten thousand li of brick and earth, watched by ten thousand ghosts.",
			"The sentinels are gone; the wall keeps watch.",
		],
		"excavation_msg": "The sentinels are gone. Clear the dust from the watchtower.",
		"fact": "The Great Wall (~200 BCE): built by millions over centuries — a dragon of brick and rammed earth curling across the mountains.",
	}


## --------------------------------------------------------------------------
## 8 · THE PARTHENON — Athens · ~432 BCE (the temple of the goddess)
## --------------------------------------------------------------------------
static func _parthenon() -> Dictionary:
	var colors := {
		"marble":   Color("#F5F0E6"),
		"bronze":   Color("#B08D3C"),
		"weathered": Color("#D8D0C0"),
		"dust":     Color("#E0C9A6"),
		"rubble":   Color("#8A7A5E"),
	}
	var core := _merge([
		_fill(-1, 1, 0, 0, 0, "marble"),   # cella
		_fill(-1, 1, 0, 0, 1, "marble"),
		_col(-1, 1, 0, 2, "marble"), _col(0, 1, 0, 2, "marble"), _col(1, 1, 0, 2, "marble"),  # porch columns
	])
	var zenith := _merge([
		_fill(-1, 1, 1, 1, 2, "marble"),   # architrave
		_fill(-1, 1, 1, 1, 3, "marble"),   # pediment base
		_col(0, 1, 4, 1, "marble"),        # pediment peak
		_col(-1, 1, 4, 1, "bronze"), _col(1, 1, 4, 1, "bronze"),  # acroteria
	])
	return {
		"id": "parthenon",
		"site_era": "The Parthenon — Athens · ~432 BCE",
		"colors": colors,
		"core": core,
		"zenith": zenith,
		"survivor": _merge([
			_col(-1, 1, 0, 1, "weathered"), _col(1, 1, 0, 1, "weathered"),
			_fill(-1, 0, 0, 0, 0, "weathered"),
		]),
		"limits": Vector3(1.0, 5.0, 1.0),
		"beat1_msg": "Marble for the goddess — set the columns of her temple.",
		"beat2_msg": "The columns are ready.\nSet the roof, the gable, the crowning bronze.",
		"epilogue": [
			"The temple has been shrine, church, mosque, and ruin — yet it stands.",
			"The gods left; the marble stayed.",
		],
		"excavation_msg": "War broke the marble. Clear the stones of the temple.",
		"fact": "The Parthenon (~432 BCE): its columns lean slightly inward — an optical illusion that makes the temple look perfectly straight.",
	}


## --------------------------------------------------------------------------
## 9 · THE COLOSSEUM — Rome · ~80 CE (the arena of an empire)
## --------------------------------------------------------------------------
static func _colosseum() -> Dictionary:
	var colors := {
		"travertine": Color("#D8C8A8"),
		"weathered":  Color("#B8A88A"),
		"dust":       Color("#D9C089"),
		"rubble":     Color("#8A7A5E"),
	}
	var core := _merge([
		_ring(-2, 2, -1, 1, 0, "travertine"),   # outer ring 5x3
		_ring(-2, 2, -1, 1, 1, "travertine"),   # second tier
	])
	var zenith := _merge([
		_col(-2, -1, 2, 1, "travertine"), _col(2, -1, 2, 1, "travertine"),
		_col(-2, 0, 2, 1, "travertine"), _col(2, 0, 2, 1, "travertine"),
		_col(-2, 1, 2, 1, "travertine"), _col(2, 1, 2, 1, "travertine"),  # upper seating, above the ring walls
	])
	return {
		"id": "colosseum",
		"site_era": "The Colosseum — Rome · ~80 CE",
		"colors": colors,
		"core": core,
		"zenith": zenith,
		"survivor": _merge([
			_ring(-2, 2, -1, 1, 0, "weathered"),
			_ring(-1, 1, 0, 0, 0, "weathered"),
		]),
		"limits": Vector3(2.0, 3.0, 1.0),
		"beat1_msg": "The arena of an empire — begin the great ring.",
		"beat2_msg": "The ring rises.\nComplete the upper seating — fifty thousand voices.",
		"epilogue": [
			"Fifty thousand voices cheered and died inside this ring.",
			"The crowd is silence; the stone still stands.",
		],
		"excavation_msg": "The city quarried the ring for its houses. Clear what the ages left.",
		"fact": "The Colosseum (~80 CE): could be flooded for mock sea battles and drained in minutes — Rome's greatest stage.",
	}


## ---- Derived views (shared by the blueprint sheet) ----

## Buildable limits derived from the FULL structure footprint (core + zenith +
## survivor) plus a one-cell margin — baseplate and placement bounds are always
## larger than anything the structure occupies (playtest rule: no floating
## blocks past the plate edge, and ghosts always readable against the grid).
static func build_limits(st: Dictionary) -> Vector3:
	var all := combined_cells(st)
	var mx := 0
	var mz := 0
	var my := 0
	for pos in all:
		mx = maxi(mx, absi(pos.x))
		mz = maxi(mz, absi(pos.z))
		my = maxi(my, pos.y)
	return Vector3(mx + 1, my + 1, mz + 1)


## Combined occupancy for the blueprint: core + zenith of a structure dict.
static func combined_cells(st: Dictionary) -> Dictionary:
	var all := {}
	for pos in st["core"]:
		all[pos] = st["core"][pos]
	for pos in st["zenith"]:
		all[pos] = st["zenith"][pos]
	return all

## Plan view: top-down (x,z) footprint per y layer. Returns {y: {Vector2i: color_name}}.
static func plan_layers(st: Dictionary) -> Dictionary:
	var layers := {}
	var all := combined_cells(st)
	for pos in all:
		var layer: int = pos.y
		if not layers.has(layer):
			layers[layer] = {}
		layers[layer][Vector2i(pos.x, pos.z)] = all[pos]
	return layers

## Elevation view (east/front): for each (z,y), occupied if any x holds a cell.
static func elevation_cells(st: Dictionary) -> Dictionary:
	var elev := {}
	var all := combined_cells(st)
	for pos in all:
		var key := Vector2i(pos.z, pos.y)
		elev[key] = all[pos]
	return elev

## Dust overlay cells: every survivor cell gets a dust mound.
static func dust_cells(st: Dictionary) -> Dictionary:
	var d := {}
	for pos in st["survivor"]:
		d[pos] = "dust"
	return d
